apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: infra-apps-project
  source:
    repoURL: git@github.com:rafalzmyslony/gitops-repo-for-sample-apps.git 
    path: flask-app-for-github-workflows/infra/monitoring  # Points to the monitoring directory
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

