apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  project: infra-apps-project
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "51.5.1"
    helm:
      parameters:
        - name: "prometheusOperator.enabled"
          value: "true"
        - name: "prometheusOperator.admissionWebhooks.enabled"
          value: "false"
        - name: "prometheusOperator.createCustomResource"
          value: "false"  #  Prevent Helm from installing CRDs
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

