apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: infra-apps-project
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.10.1
    chart: grafana
    helm:
      values: |
        persistence:
          enabled: true
          storageClassName: "standard"
          accessModes:
            - ReadWriteOnce
          size: 10Gi
        adminUser: admin
        adminPassword: "admin"
        ingress:
          enabled: true
          hosts:
            - grafana.example.com
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
        # Configure dashboard provider
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: "default"
                orgId: 1
                folder: ""
                type: file
                disableDeletion: false
                updateIntervalSeconds: 10
                options:
                  path: /var/lib/grafana/dashboards
        # Mount external ConfigMaps
        extraConfigmapMounts:
          - name: grafana-datasources
            mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
            subPath: datasources.yaml
            configMap: grafana-datasources
            readOnly: true
          - name: grafana-dashboards
            mountPath: /var/lib/grafana/dashboards
            configMap: grafana-dashboards
            readOnly: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true