apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-apps
  namespace: argocd
spec:
  project: infra-apps-project 
  source:
    repoURL: git@github.com:rafalzmyslony/gitops-repo-for-sample-apps.git 
    path: flask-app-for-github-workflows/infra/argocd-apps  # Directory where application definitions live
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

